# SwiftLint Configuration for hyperliquid-swift

excluded:
  - .build
  - Package.swift

disabled_rules:
  - trailing_comma
  - identifier_name
  - force_cast
  - force_try
  - line_length
  - file_length
  - type_body_length
  - function_body_length
  - cyclomatic_complexity
  - opening_brace
  - discouraged_optional_boolean

opt_in_rules:
  - empty_count
  - empty_string
  - closure_spacing
  - first_where
  - last_where
  - modifier_order
  - redundant_nil_coalescing
  - sorted_first_last
  - toggle_bool
  - yoda_condition

function_parameter_count:
  warning: 8
  error: 10

nesting:
  type_level: 3
  function_level: 4

large_tuple:
  warning: 4
  error: 6

reporter: "xcode"
